### ISSUE TITLE
Multiple environements

### ISSUE THREAD

**Issue by florentcm** [chrishepner/env-extension#1]
Hi, great job, I found this extension very useful. I'd like to contribute to add multiple environments notifiers.

Banner is great, but IMO, I would prefer something less intrusive like changing a color of a small indicator in the address bar. Are planning to improve the extension soon?

**Comment by chrishepner** [comment]
Hi,

Thanks, glad you find it useful!

I don't have plans to add this in the immediate future. However, if you'd like to work on this I'd welcome a pull request.

This would probably need the following:
- Badge https://developer.chrome.com/extensions/browserAction#badge
- Toggle in extension settings to enable/disable badge
- Toggle in extension settings to enable/disable banner
